//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftSeatConfig
    {
        public int ConfigID { get; set; }
        public int AircraftID { get; set; }
        public int SeatClassID { get; set; }
        public int SeatCount { get; set; }
        public Nullable<int> RowStart { get; set; }
        public Nullable<int> RowEnd { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual SeatClass SeatClass { get; set; }
    }
}
