//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long LogID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string TableName { get; set; }
        public string Operation { get; set; }
        public string RecordID { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
    
        public virtual User User { get; set; }
    }
}
