//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPromotion
    {
        public int BookingPromotionID { get; set; }
        public int BookingID { get; set; }
        public int PromotionID { get; set; }
        public decimal DiscountAmount { get; set; }
        public Nullable<System.DateTime> AppliedAt { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
