//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightPricing
    {
        public int PricingID { get; set; }
        public int FlightID { get; set; }
        public int SeatClassID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> BookedSeats { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual SeatClass SeatClass { get; set; }
    }
}
