//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int HistoryID { get; set; }
        public int PaymentID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public string Note { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
