//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeatClass()
        {
            this.AircraftSeatConfigs = new HashSet<AircraftSeatConfig>();
            this.FlightPricings = new HashSet<FlightPricing>();
            this.Seats = new HashSet<Seat>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int SeatClassID { get; set; }
        public string ClassName { get; set; }
        public string DisplayName { get; set; }
        public decimal PriceMultiplier { get; set; }
        public Nullable<int> BaggageAllowance_KG { get; set; }
        public Nullable<int> CabinBaggageAllowance_KG { get; set; }
        public string Description { get; set; }
        public string Features { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AircraftSeatConfig> AircraftSeatConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightPricing> FlightPricings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
