//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public System.Guid TicketID { get; set; }
        public int BookingFlightID { get; set; }
        public int PassengerID { get; set; }
        public int SeatClassID { get; set; }
        public string TicketNumber { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CheckedInAt { get; set; }
        public string SeatNumber { get; set; }
    
        public virtual BookingFlight BookingFlight { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual SeatClass SeatClass { get; set; }
    }
}
